### ISSUE TITLE
리팩토링 방향성

### ISSUE THREAD

**Issue by wkd-woo** [travel-service/backend#13]
현재 Location은 memberLocation 수정, selectedLocation 조회 기능만 남겨둔 상태. 7/17 이전에 마무리 지을 계획입니다.

+ 리팩토링 관련해서 의견 남깁니다.

++
현재 애플리케이션은 인터페이스 의존을 하고있지 않은 구조로 보입니다.
스프링 핵심가치인 IoC를 적극 활용하지 못하고 있는데

전체적으로 리팩토링 해야할 필요가 있다고 생각합니다.
설명을 위해 image 첨부합니다.

![image](https://user-images.githubusercontent.com/68547545/178145079-9ab4a0a1-5301-4653-89c6-e2da9a12a41f.png)

![image](https://user-images.githubusercontent.com/68547545/178145065-820ff074-4c7f-45e9-838c-f73d39ca85b8.png)

 
참고: https://mangkyu.tistory.com/194#:~:text=SOLID%EB%9E%80%20%EA%B0%9D%EC%B2%B4%20%EC%A7%80%ED%96%A5%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D,%EA%B8%80%EC%9E%90%EB%A5%BC%20%EB%94%B0%EC%84%9C%20%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A1%8C%EB%8B%A4.

0. 현재 각 레이어마다 추상화된 interface에 의존하고 있지 않고 구현체에 의존하고 있음.
1. 때문에 객체지향 5원칙 Solid를 준수하는 구조가 아님.
2. 이것이 왜 문제가 되는가? -> 한 레이어에 로직을 수정하면 다른 레이어에도 영향을 미친다. 관심사의 분리 또한 충분히 되고 있지 않음. 
3 결론. 추상화에 의존하는 방식으로 리팩토링 진행하겠습니다.

![image](https://user-images.githubusercontent.com/68547545/178145099-b04d16b3-b43a-4feb-949b-2a4526f0c641.png)
김영한님의 Spring boot 강의자료 참고자료로 첨부합니다 (코드로 배우는 스프링 부트)

+++ 메소드와 파라미터 명명에 일관성이 조금 더 있으면 좋겠습니다.
param으로 받은 id가 어떤 객체의 id인지 직관적으로 이해하기 어려운 부분이 있습니다.

**Comment by Lee-JongSoo** [comment]
plan 파트 리펙토링 완료
