### ISSUE TITLE
Restful한 API URI로 리팩토링 예정(due. 7/20)

### ISSUE THREAD

**Issue by wkd-woo** [travel-service/backend#17]
한개의 단건조회
GET /directories/{directory-id}

이름 변경
POST /directories/{directory-id}/name

디렉토리 생성
POST /directories

플랜 살리기
POST /directories/main
플랜 쓰레기통 이동
POST /directories/trash

플랜 특정 디렉토리로 이동
POST /directories/{directory-id}/plans

완전삭제
POST directories/plans

유저 디렉토리 요소 불러오기
GET /directories/members

MAIN 디렉토리
GET /directories/main
TRASH 디렉토리
GET /directories/trash

################

POST members/{memberId}/profile

POST members/{memberId}/profile/bio

POST members/{memberId}/profile/img

POST members/{memberId}/profile/password

**Comment by Lee-JongSoo** [comment]
plan 파트 리펙토링 완료
